// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/18/2025, 11:30:49 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/Reaper X/Desktop/eyus-portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Reaper X/Desktop/eyus-portfolio/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Reaper X/Desktop/eyus-portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Reaper X/Desktop/eyus-portfolio/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Reaper X/Desktop/eyus-portfolio/plugins/**/*.{js,ts,mjs}","C:/Users/Reaper X/Desktop/eyus-portfolio/composables/**/*.{js,ts,mjs}","C:/Users/Reaper X/Desktop/eyus-portfolio/utils/**/*.{js,ts,mjs}","C:/Users/Reaper X/Desktop/eyus-portfolio/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Reaper X/Desktop/eyus-portfolio/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Reaper X/Desktop/eyus-portfolio/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Reaper X/Desktop/eyus-portfolio/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;