// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/1/2026, 10:04:32 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/eyug/eyus-portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/eyug/eyus-portfolio/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/eyug/eyus-portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/eyug/eyus-portfolio/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/eyug/eyus-portfolio/plugins/**/*.{js,ts,mjs}","/home/eyug/eyus-portfolio/composables/**/*.{js,ts,mjs}","/home/eyug/eyus-portfolio/utils/**/*.{js,ts,mjs}","/home/eyug/eyus-portfolio/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/eyug/eyus-portfolio/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/eyug/eyus-portfolio/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/eyug/eyus-portfolio/app.config.{js,ts,mjs}","/home/eyug/eyus-portfolio/app/spa-loading-template.html"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;